In [1]:
import os
import time
import numpy as np

import sys 
sys.path.append('../python')
from lorenzetti_utils import *

import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

In [2]:
if not os.path.exists('json_files'): os.mkdir('json_files')
save_path       = os.path.abspath('json_files') 
print(save_path)
file_name       = 'lorenzetti_cells_dict'
scale           = 1*1e4
nominal_radius  = 1*scale
calo_radius     = np.array([0.15, 0.3, 0.03, 0.4, 0.4, 0.2])*scale
layer_info_dict = {
    'nominal_size'       : 3*scale,
    # Electromagnetic Layers
    'EM1'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius[0].sum(),
        'delta_eta'      : 0.003,
        'delta_phi'      : 0.1,
    }, 
    'EM2'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius[:2].sum(),
        'delta_eta'      : 0.025,
        'delta_phi'      : 0.025,
    },
    'EM3'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius[:3].sum(),
        'delta_eta'      : 0.050,
        'delta_phi'      : 0.025,
    },
    # Hadronic Layers
    'HAD1'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius[:4].sum(),
        'delta_eta'      : 0.1,
        'delta_phi'      : 0.1,
    }, 
    'HAD2'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius[:5].sum(),
        'delta_eta'      : 0.1,
        'delta_phi'      : 0.1,
    },
    'HAD3'  : {
        'max_dist_to_ip' : nominal_radius + calo_radius.sum(),
        'delta_eta'      : 0.2,
        'delta_phi'      : 0.1,
    }
}

/home/micaelverissimo/Workspace/simulador/lorenzet/lorenzet/share/json_files


In [3]:
lorenzetti_ = lorenzetti_cells_grid_builder(layer_info_dict)

In [4]:
%time
lorenzetti_.get_all_cell_centers()

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 7.39 µs


In [5]:
lorenzetti_.dump_dict(path=save_path, name=file_name)

In [6]:
vector_samples = 2.5 * np.random.randn(5, 3) + 3
print(vector_samples)

[[ 3.71626195  5.51779341  2.63805027]
 [ 4.41351527  3.09754506  1.99706403]
 [ 6.74848935  4.53815202  3.94998187]
 [ 6.61316763  1.10562262 -0.1156418 ]
 [ 7.78666546  4.41633036  1.55413576]]


In [7]:
atlas_coord = transform_to_ATLAS_coord(vector_samples)
print(atlas_coord)

[[6.65256695 0.97807436 0.66073087]
 [5.39202211 0.61195426 0.43831775]
 [8.13246164 0.59200907 0.55619059]
 [6.70495246 0.16565299 0.01748571]
 [8.95187873 0.51592674 0.19828745]]
